name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: pnpm install, build, and test
        run: |
          pnpm --frozen-lockfile install
          pnpm build
          pnpm test -w false --coverage
          pnpm lint
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
        env:
          CI: true
